### ISSUE TITLE
Le dossier Executable manquant

### ISSUE THREAD

**Issue by digitsarl** [digitsarl/devC#1]
Hello @bleriot-tchamba ,
Il est dit dans le readme qu'il faut le dossier Executable. Mais je ne le trouve dans l'arbre des sources. Est-ce une erreur? Merci de vérifier.

**Comment by bleriot-tchamba** [comment]
Bonjour Monsieur,
D'accord je vérifie.
Je vais mettre le readme à jour aussi

cordialement Bleriot Betndam

**Comment by digitsarl** [comment]
Hello. Du nouveau?

**Comment by bleriot-tchamba** [comment]
Bonjour Monsieur,
Le problème du dossier manquant a été reglé, et aussi j'ai mi le readme à
jour

cordialement Bleriot Betndam

**Comment by digitsarl** [comment]
OK, je vois. Cela va mieux en tout cas.
Je ferme pour le moment le ticket

**Comment by digitsarl** [comment]
Ok, bien existant.

**Comment by bleriot-tchamba** [comment]
D'accord Monsieur

Le mer. 14 sept. 2022 à 13:46, DiGIT Ltd ***@***.***> a
écrit :
