### ISSUE TITLE
Confirmation de sortie dans le Main si on change de fichier 

### ISSUE THREAD

**Issue by digitsarl** [digitsarl/devC#2]
Hello @bleriot-tchamba, Il faudrait bien voir dans le code que le changement du nom de fichier d'entrée, par exemple "data/observations_externes.txt" et pour une sortie dans "/data/factsExtern.ttl" est bien écrit dans la sortie. L'objectif étant de voir les différentes sorties en fonction des input.

**Comment by bleriot-tchamba** [comment]
D'accord Monsieur, je comprends.

Je propose donc qu'en exécutant le programme, l'utilisateur mentionne le
nom du fichier d'entrée et celui du fichier de sortie et ainsi la
modification des sorties sera dynamique.

Si cela vous arrange, je modifie le code de cette façon et par conséquent
le redame.

Cordialement Bleriot Betndam.

**Comment by digitsarl** [comment]
Parfait. En attente des modifications.
Et aussi, préciser dans le readme d'executer `make clean` si le repo /obj existe avant de lancer `make ./executable/Main`

**Comment by bleriot-tchamba** [comment]
D'accord

**Comment by bleriot-tchamba** [comment]
Bonjour Monsieur, j'ai mis à jour le code et le readme.

Dorénavant l'utilisateur devra renseigner le nom du fichier en entrée et
celui du fichier en sortie.

Aussi, j'ai créé un nouveau dossier qui contiendra désormais les fichiers
en sortie.

Aussi, par rapport à la commande make clean que vous m'avez demandé
d'ajouter dans le readme, je pense que ce n'est pas nécessaire car  à
chaque fois que l'utilisateur tape la commande make, le dossier obj/ est
d'abord supprimé (s'il existe) avant le lancement d'une nouvelle
compilation.

**Comment by bleriot-tchamba** [comment]
Monsieur,

Dans le fichier que vous aviez ajouté dans le drive, les observations
commençaient par  "2022-08-19" . Ici, les éléments de la date sont séparés
par un tiret de 6 (-) contrairement aux fichiers à  base desquels j'avais
écris le code où les éléments de la date étaient séparés par le slash ( / ).

Voulez-vous qu'on considère finalement le tiret de 6 ou le slash?

**Comment by digitsarl** [comment]
oui, il faut s'adapter en fonction du fichier. Merci donc de modifier le code en fonction du séparateur.

**Comment by bleriot-tchamba** [comment]
D'accord Monsieur
